language: go
arch:
  - amd64
  - ppc64le
go:
  - tip
  - 1.8
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2
  # Disable GO version 1.2,1.3 &1.4
jobs:
  exclude:
    - arch: amd64
    - arch: ppc64le
      go: 1.2
    - arch: ppc64le
      go: 1.3
    - arch: ppc64le
      go: 1.4
notifications:
  email:
    on_success: change
    on_failure: always
